In [84]:
import numpy as np
from utils.dataloader import *
from utils.coordinate_calibration import PointCloudRegistration
from utils.meshgrid import Meshgrid
from utils.icp import IterativeClosestPoint, Matching
from utils.deformable_icp import DeformableICP

In [85]:
OUTPUT_DIR = '../OUTPUT'
DATA_DIR = './pa345_data'

RIGID_BODY_DATA_A = f'{DATA_DIR}/Problem5-BodyA.txt'
RIGID_BODY_DATA_B = f'{DATA_DIR}/Problem5-BodyB.txt'

SURFACE_DATA = f'{DATA_DIR}/Problem5MeshFile.sur'

SAMPLE_ID = 'A'
SAMPLE_DATA = f'./pa345_data/PA5-{SAMPLE_ID}-Debug-SampleReadingsTest.txt'
# SAMPLE_DATA = f'./pa345_data/PA5-{SAMPLE_ID}-Unknown-SampleReadingsTest.txt'

# Load data files
rigidbody_dl_A = RigidBodyDataloader.read_file(RIGID_BODY_DATA_A)
rigidbody_dl_B = RigidBodyDataloader.read_file(RIGID_BODY_DATA_B)

surface_dl = Surfaceloader.read_file(SURFACE_DATA)
sample_dl = SampleReadingsDataloader.read_file(SAMPLE_DATA, delimiter=',', N_A=rigidbody_dl_A.N_markers, N_B=rigidbody_dl_B.N_markers)

modes_dl = AtlasModesDataloader.read_file(f'{DATA_DIR}/Problem5Modes.txt')
print(modes_dl.modes.shape)

First element of modes: [[-23.786148 -16.420282 -48.22999 ]
 [-20.396912 -12.622053 -49.39456 ]
 [-23.783207  -9.689573 -49.930054]
 ...
 [ 22.470142   0.870029  43.12947 ]
 [ 17.788347  -3.268495  51.15235 ]
 [ 18.91166   15.439708  58.151134]]
Last element of modes: [[ 0.008493  0.007182  0.016331]
 [ 0.006277  0.008463  0.013969]
 [ 0.005167  0.001916  0.020395]
 ...
 [ 0.005625  0.002305 -0.014911]
 [ 0.000907  0.004757 -0.017129]
 [ 0.016631  0.005701 -0.000242]]
(7, 1568, 3)


### Get F<sub>A, k</sub> and F<sub>B, k</sub>

In [86]:
rigidbody_dl_A_markers = rigidbody_dl_A.markers.reshape(1, -1, 3) # markers of body A in body A coordinates

sample_dl_A = sample_dl.body_A # samples of body A markers in tracker coordinates
num_samples = sample_dl.N_samps

# perform registration for each frame
reg = PointCloudRegistration(verbose=False)
F_A = []
for i in range(num_samples):
    sample_dl_A_i = sample_dl_A[i].reshape(1, -1, 3)
    F_A_i, err = reg.register(rigidbody_dl_A_markers, sample_dl_A_i)
    F_A.append(F_A_i)

F_A = np.array(F_A)

ridigbody_dl_B_markers = rigidbody_dl_B.markers.reshape(1, -1, 3) # markers of body B in body B coordinates
sample_dl_B = sample_dl.body_B # samples of body B markers in tracker coordinates

# perform registration for each frame
F_B = []
for i in range(num_samples):
    sample_dl_B_i = sample_dl_B[i].reshape(1, -1, 3)

    F_B_i, err = reg.register(ridigbody_dl_B_markers, sample_dl_B_i)
    F_B.append(F_B_i)

F_B = np.array(F_B)

### Get d<sub>k</sub>

In [87]:
A_tip = rigidbody_dl_A.tip
A_tip = np.append(A_tip, 1) # add 1 for homogenous coordinates
d_k = []

for i in range(num_samples):
    F_A_i = F_A[i] # get F_A for frame i
    F_B_i_inv = np.linalg.inv(F_B[i]) # get F_B inverse for frame i

    d_k.append(F_B_i_inv @ F_A_i @ A_tip) # d_k = F_B^-1 * F_A * A_tip

d_k = np.array(d_k)[:,:3]
print(d_k.shape)

(150, 3)


### Compute s<sub>k</sub>, c<sub>k</sub>

In [88]:
# Initialize ICP helper class 
deform_icp = DeformableICP()

# Initialize meshgrid of Triangles
mesh = Meshgrid(surface_dl.vertices, surface_dl.triangles)

best_pt_cloud, closest_pt, dist, F_best, λ_best = deform_icp(d_k, mesh, modes_dl.modes)


Performing rigid-body ICP...


11it [00:01<00:23,  8.21it/s, match=1.37, prev_match_ratio=0.998]


Done.


Performing deformable ICP...


17it [00:02<00:22,  8.12it/s, match=0.441, prev_match_ratio=0.995]


Done.



### write output to file

In [89]:
output_file = f'{OUTPUT_DIR}/pa5-{SAMPLE_ID}-Output.txt'
with open(output_file, 'w') as file:
    file.write(f"{num_samples}, {output_file}\n")
    file.write(" ".join(map(lambda x: f"{x:.4f}", λ_best[1:])) + "\n")
    for sample in range(num_samples):
        file.write(f"{best_pt_cloud[sample][0]:.2f} {best_pt_cloud[sample][1]:.2f} {best_pt_cloud[sample][2]:.2f} ")
        file.write(f"{closest_pt[sample][0]:.2f} {closest_pt[sample][1]:.2f} {closest_pt[sample][2]:.2f}")
        file.write(f" {dist[sample]:.2f}")
        file.write("\n")

print(f"Output written to {output_file}")


Output written to ../OUTPUT/pa5-K-Output.txt
